# https://docs.docker.com/compose/yml/

syncthing:
  container_name: syncthing
  hostname: syncthing
  image: joeybaker/syncthing
  ports:
    - "22000:22000"
    - "8080:8080"
    - "21025:21025/udp"
  volumes:
    - /srv/docker/syncthing/data:/srv/data
    - /srv/docker/syncthing/config:/srv/config
  restart: always
